name: Build and Push dist to OSS
on:
  release:
    types: [created]
# ä½¿ç”¨å¹¶å‘å–æ¶ˆä»»ä½•å½“å‰ä½œä¸šæˆ–è¿è¡Œ
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: ä»Žtagä¸­è§£æžå‡ºå½“å‰æž„å»ºçš„åˆ†æ”¯ï¼Œä»“åº“ç­‰ï¼Œå¹¶æš´éœ²åˆ°çŽ¯å¢ƒå˜é‡ä¸­
        uses: threfo/tag-parse-action@master
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}

      - name: æ‹‰å–ç§æœ‰ä»“åº“çš„ä»£ç 
        uses: actions/checkout@master
        with:
          repository: threfo/${{ env.REPOSITORY }}
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ env.BRANCH }}
      
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/tcloud.key
          chmod 600 ~/.ssh/tcloud.key
          cat >>~/.ssh/config <<END
          Host tcloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/tcloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_KEY: ${{ secrets.SERVER_SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
      - name: è¿è¡Œå‘½ä»¤
        run: |
          ssh -q tcloud <<EOF
            ${{ env.RUN_COMMAND }}
          EOF
  

      - name: æž„å»ºæˆåŠŸæ¶ˆæ¯
        if: ${{ success() }}
        uses: threfo/work-wechat-msg@main
        with:
          botKey: ${{ secrets.WORK_WECHAT_GITHUB_ROBOT_KEY }}
          content: ðŸŽ‰ é¡¹ç›®${{ env.REPOSITORY }}ï¼Œåˆ†æ”¯${{ env.BRANCH }}, æž„å»ºå‘½ä»¤${{ env.RUN_COMMAND }} æž„å»ºæˆåŠŸã€‚--- Github Actions
        
      - name: æž„å»ºå¤±è´¥æ¶ˆæ¯
        if: ${{ failure() }}
        uses: threfo/work-wechat-msg@main
        with:
          botKey: ${{ secrets.WORK_WECHAT_GITHUB_ROBOT_KEY }}
          content: âŒ é¡¹ç›®${{ env.REPOSITORY }}ï¼Œåˆ†æ”¯${{ env.BRANCH }}, æž„å»ºå‘½ä»¤${{ env.RUN_COMMAND }} æž„å»ºå¤±è´¥ã€‚--- Github Actions
        
  




